version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
      # terraform-plugin-go should only be updated via terraform-plugin-framework
      - dependency-name: "github.com/hashicorp/terraform-plugin-go"
      # terraform-plugin-log should only be updated via terraform-plugin-framework
      - dependency-name: "github.com/hashicorp/terraform-plugin-log"
      # go-hclog should only be updated via terraform-plugin-log
      - dependency-name: "github.com/hashicorp/go-hclog"
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
  - package-ecosystem: "gomod"
    directory: "/.ci/providerlint"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/.ci/tools"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/skaff"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/infrastructure/repository"
    schedule:
      interval: "daily"
