name: Autoremove Labels

on:
  issues:
    types: [closed, opened]
  pull_request_target:
    types: [closed]

env:
  IN_MAINTAINER_LIST: ${{ contains(secrets.MAINTAINER_LIST, github.actor) }}

jobs:
  RemoveNeedsTriageFromMaintainers:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Remove needs-triage label from member's Issues
        if: fromJSON(env.IN_MAINTAINER_LIST)
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            needs-triage

  RemoveTriagingLabelsFromClosedIssueOrPR:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Remove triaging labels from closed issues and PRs
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            needs-triage
            waiting-response
